FROM python:3.10-slim

RUN apt-get update && apt-get install -y gcc g++ librdkafka-dev

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python"]